Up pipeline

diff --git a/.github/workflows/docker-build-push.yml b/.github/workflows/docker-build-push.yml
--- a/.github/workflows/docker-build-push.yml
+++ b/.github/workflows/docker-build-push.yml
@@ -37,7 +37,27 @@ jobs:
       
       - name: Push Docker image to Harbor
         run: |
-          docker push harbor.gambiarras.website/automate/auto-landing-page:${{ github.run_number }}
+          MAX_RETRIES=5
+          RETRY_COUNT=0
+          PUSH_SUCCESSFUL=false
+          
+          while [ $RETRY_COUNT -lt $MAX_RETRIES ] && [ "$PUSH_SUCCESSFUL" = "false" ]; do
+            echo "Attempt $(($RETRY_COUNT + 1)) of $MAX_RETRIES to push image to Harbor..."
+            
+            if docker push harbor.gambiarras.website/automate/auto-landing-page:${{ github.run_number }}; then
+              PUSH_SUCCESSFUL=true
+              echo "Push successful!"
+            else
+              RETRY_COUNT=$(($RETRY_COUNT + 1))
+              if [ $RETRY_COUNT -lt $MAX_RETRIES ]; then
+                echo "Push failed. Retrying in 30 seconds..."
+                sleep 30
+              else
+                echo "All $MAX_RETRIES attempts failed."
+                exit 1
+              fi
+            fi
+          done
           
       - name: Image digest
         run: echo ${{ steps.docker_build.outputs.digest }}
